security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto
        App\Entity\Client:
            algorithm: auto
        App\Entity\Manager:
            algorithm: auto


    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        app_client_provider:
            entity:
                class: App\Entity\Client
                property: email
        app_manager_provider:
            entity:
                class: App\Entity\Manager
                property: email
        app_users:
            chain:
                providers: [ 'app_user_provider','app_client_provider','app_manager_provider' ]


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            provider: app_users
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            login_throttling:
                max_attempts: 5

        api:
            pattern: ^/api
            stateless: true
            provider: app_users
            jwt: ~


    access_control:
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api, roles: PUBLIC_ACCESS }


    role_hierarchy:
        ROLE_SUPER_ADMIN: ['ROLE_ADMIN','ROLE_USER']
        ROLE_ADMIN: ['ROLE_USER']
